### PR TITLE
Replace travis & python-publish with full CI/CD GitHub Actions setup

### PR DESCRIPTION
**Pull request by rlaphoenix**
This moves from a mix of Travis-CI and GitHub Actions to full GitHub Actions.

Now, when releasing, you simply need to tag a commit with the tag starting with `v`, e.g., `v1.4.0`. It will then automatically build a wheel, make a GitHub release, attach the wheel to the GitHub release, then publish the Wheel and Srcdist to PyPI. You should update the version in setup.py, changelogs, etc, before tagging. A side benefit is that it also automatically creates a generic changelog based on the commits since the previous release.

The CI workflow does the same as what the travis workflow did.

**Note**: The CI workflow will do tests on 2.7 and 3.3 to 3.10. You may want to change those. However, based on whats in the setup.py etc, I assume all these versions are still supported and wanted to be tested.

The CD workflow has been rigorously tested on many of my other Projects. However, the only thing that isn't fully tested is the way you used `pypa/gh-action-pypi-publish` to publish to PyPI. I personally use either `poetry publish` (not relevant to this repository) or `twine` to publish. I kept using `pypa/gh-action-pypi-publish` as your other workflow used it so I presume it's good to go.

However, the CI workflow may end up failing some builds as it has never been tested. I say it may fail, because I'm not certain your project and all the tests will be successful on all these versions as listed earlier. But the workflow itself should be good. Do note that you may or may not want coverage to be tested in CI, but that's up to you. I left it in for now as your travis workflow used it so I presume you want it.

On pulling I expect that the CI workflow may fail on some versions due to tests or coverage, or maybe all versions. However, the CI workflow itself should be fine. The CD workflow I expect to be fully working as long as `pypa/gh-action-pypi-publish` as you used it, works.

### CODE REVIEW

**Comment by rlaphoenix** [comment]
I've changed the CI workflow to use ubuntu-20.04 which supports all the 3.x versions used. Ubuntu-latest (22.04) only supports Python 3.7.14+.

**Comment by rlaphoenix** [comment]
Hmm, it seems as if ubuntu-20.04 only supports 2.7 and 3.5.4+. We could use ubuntu-18.04, or just drop support for older Python versions that are no longer supported. It's up to you.

**Comment by beardypig** [comment]
I'm fine dropping support for EOL versions

**Comment by rlaphoenix** [comment]
I thought about it and I feel like dropping support should be done outside of this pull request. So what I did was use ubuntu-18.04 to have support for all versions, and you could drop support afterward in all areas needing changes (setup.py, readme badges, e.t.c). For ubuntu-latest support, you need to ditch Python 2 completely, then drop support for Python 3.6 and older. Python 3.7 is end-of-life in 2 months, so you could also pre-emptively drop support for Python 3.7, a lot of other libraries and projects are doing exactly that including my own.

**Comment by rlaphoenix** [comment]
Seems 3.6+ are now installing but failing some tests.
3.4 are 3.5 are failing during the installation of construct 2.8.8 (yet it looks like it should be fine?).
I think it's more or less ready to pull, just after pulling this we would need to begin fixing those tests, verifying support up to 3.10, and dropping those that fail.

You should also consider moving to a poetry-based project, see my fork here which has already done that: https://github.com/rlaphoenix/pymp4/blob/master/pyproject.toml

It's much much much nicer to work with than setuptools.

**Comment by beardypig** [comment]
Cool, I hadn't seen poetry before, it looks nice. I've been out of the loop for the last couple of years. 

OK, let's merge it and fix the tests :)

**Comment by rlaphoenix** [comment]
Hi, could you pull it then haha?

Once you pull I'll work on moving to poetry + dropping older versions at the same time.

**Pull request merged**
